name: Automated Vulnerability Scan

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**.py'
      - 'Dockerfile'
      - '**.yaml'
      - '**.yml'
      - '**.tf'
  pull_request:
    branches:
      - main
      - dev

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt.txt

      - name: Install Nmap
        run: sudo apt-get update && sudo apt-get install -y nmap

      - name: Run Vulnerability Scanner
        run: |
          python main.py --ci
